name: "Mix Depdendency Submission"
description: "Calculates dependencies for Mix and submits the list to the GitHub Dependency Submission API"
author: "Jonatan Männchen"
branding:
  icon: arrow-up
  color: blue
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  project-path:
    required: true
    description: "Repo path to the rebar.lock file used to detect dependencies. Defaults to rebar.lock in the root of the repository."
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - name: "Download Dependency Submission Tool"
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
      with:
        repository: "maennchen/mix-dependency-submission"
        tag: "v1.0.0-beta.5"
        fileName: "mix_dependency_submission_linux_amd64"
        out-file-path: "${{ runner.temp }}"
    - name: "Verify Dependency Submission Tool Provenance"
      run: |
        gh attestation \
          verify \
          --repo maennchen/mix-dependency-submission \
          "${{ runner.temp }}/mix_dependency_submission_linux_amd64"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: "Make Tool Executable"
      run: "chmod +x mix_dependency_submission_linux_amd64"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
    - name: "Submit Dependencies"
      run: |
        ${{ runner.temp }}/mix_dependency_submission_linux_amd64 \
          --project-path="${{ inputs.project-path }}" \
          --github-token="${{ inputs.token }}"
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ github.token }}
