name: "Mix Depdendency Submission"
description: "Calculates dependencies for Mix and submits the list to the GitHub Dependency Submission API"
author: "Jonatan Männchen"
branding:
  icon: arrow-up
  color: blue
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  project-path:
    required: true
    description: "Repo path to the mix.exs file used to detect dependencies. Defaults to mix.exs in the root of the repository."
    default: "${{ github.workspace }}"
  install-deps:
    required: false
    description: "Whether to install dependencies to improve Submission Quality."
    default: "false"
  ignore:
    required: false
    description: "Paths to ignore"
runs:
  using: "composite"
  steps:
    - name: "Download Dependency Submission Tool"
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
      with:
        repository: "maennchen/mix-dependency-submission"
        tag: "v1.0.0-beta.6"
        fileName: "mix_dependency_submission_linux_amd64"
        out-file-path: "${{ runner.temp }}"
    - name: "Verify Dependency Submission Tool Provenance"
      run: |
        gh attestation \
          verify \
          --repo maennchen/mix-dependency-submission \
          "${{ runner.temp }}/mix_dependency_submission_linux_amd64"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: "Make Tool Executable"
      run: "chmod +x mix_dependency_submission_linux_amd64"
      shell: "bash"
      working-directory: "${{ runner.temp }}"
    - name: "Submit Dependencies"
      run: |
        ${{ runner.temp }}/mix_dependency_submission_linux_amd64 \
          --project-path="$PROJECT_PATH" \
          --github-token="$GITHUB_TOKEN" \
          ${{ inputs.install-deps == 'true' && '--install-deps' || '' }} \
          --ignore "$IGNORE"
      shell: "bash"
      env:
        GITHUB_TOKEN: "${{ inputs.token }}"
        PROJECT_PATH: "${{ inputs.project-path }}"
        IGNORE: "${{ inputs.ignore }}"
