on:
  push:
    branches:
      - "main"

name: "Main Branch"

permissions:
  contents: read

jobs:
  test:
    name: "Test"

    permissions:
      contents: read
      security-events: write

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"
    
    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_build.yml
    with:
      attest: false

  docs:
    name: "Docs"
    
    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_docs.yml
    with:
      attest: false

  report_deps:
    name: "Report Dependencies"

    needs: ['build']

    permissions:
      contents: write

    uses: ./.github/workflows/part_report_deps.yml
