on:
  push:
    branches:
      - "main"

name: "Main Branch"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  report_deps:
    name: "Report Dependencies"

    needs: ['build']

    uses: ./.github/workflows/part_report_deps.yml
