on:
  workflow_call:
    inputs:
      attest:
        description: "Attest the build"
        default: true
        type: boolean

name: "Build"

permissions:
  contents: read

jobs:
  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    env:
      MIX_ENV: prod

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-runtime-env
        with:
          mix-env: prod

      - run: mix escript.build
      - name: "Attest provenance"
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        id: attest-provenance
        if: "${{ github.event.inputs.attest }}"
        with:
          subject-path: 'mix_dependency_submission'
      - name: "Copy provenance"
        if: "${{ github.event.inputs.attest }}"
        run: cp "$ATTESTATION" mix_dependency_submission.sigstore
        env:
          ATTESTATION: "${{ steps.attest-provenance.outputs.bundle-path }}"
      
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: escript
          path: mix_dependency_submission*

