on:
  workflow_call:
    inputs:
      attest:
        description: "Attest the build"
        default: true
        type: boolean

name: "Build"

permissions:
  contents: read

jobs:
  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    env:
      MIX_ENV: prod

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-runtime-env
        with:
          mix-env: prod

      - run: mix escript.build
      - name: "Attest provenance"
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        id: attest-provenance
        if: "${{ inputs.attest }}"
        with:
          subject-path: 'mix_dependency_submission'
      - name: "Copy provenance"
        if: "${{ inputs.attest }}"
        run: cp "$ATTESTATION" mix_dependency_submission.sigstore
        env:
          ATTESTATION: "${{ steps.attest-provenance.outputs.bundle-path }}"
      
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: escript
          path: mix_dependency_submission*

