on:
  workflow_call:
    inputs:
      releaseName:
        required: false
        type: string
    secrets:
      HEX_API_KEY:
        required: false

name: "Publish"

permissions:
  contents: read

jobs:
  hex_publish:
    name: mix hex.publish

    runs-on: ubuntu-latest

    if: "${{ inputs.releaseName }}"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-runtime-env

      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
