on:
  workflow_call:
    inputs:
      attest:
        description: "Attest the build"
        default: true
        type: boolean

name: "Documentation"

permissions:
  contents: read

jobs:
  generate:
    name: "Generate"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ./.github/actions/setup-runtime-env

      - run: mix docs
      - name: "Create Docs Archive"
        run: |
          tar -czvf docs.tar.gz doc
      
      - name: "Attest docs provenance"
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        id: attest-docs-provenance
        if: "${{ github.event.inputs.attest }}"
        with:
          subject-path: 'docs.tar.gz'
      - name: "Copy docs provenance"
        if: "${{ github.event.inputs.attest }}"
        run: cp "$ATTESTATION" docs.tar.gz.sigstore
        env:
          ATTESTATION: "${{ steps.attest-docs-provenance.outputs.bundle-path }}"

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: docs
          path: docs.tar.gz*