on:
  workflow_call:
    inputs:
      attest:
        description: "Attest the build"
        default: true
        type: boolean

name: "Build"

permissions:
  contents: read

jobs:
  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    env:
      MIX_ENV: prod

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-runtime-env
        with:
          mix-env: prod

      - run: mix escript.build
      - name: "Attest provenance"
        uses: actions/attest-build-provenance@520d128f165991a6c774bcb264f323e3d70747f4 # v2.2.0
        id: attest-provenance
        if: "${{ inputs.attest }}"
        with:
          subject-path: 'mix_dependency_submission'
      - name: "Copy provenance"
        if: "${{ inputs.attest }}"
        run: cp "$ATTESTATION" mix_dependency_submission.sigstore
        env:
          ATTESTATION: "${{ steps.attest-provenance.outputs.bundle-path }}"
      
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: escript
          path: mix_dependency_submission*

