on:
  workflow_call: {}

name: "Test"

env:
  BUILD_EMBEDDED: true

jobs:
  format:
    name: Check Formatting

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: '.tool-versions'
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v3
        with:
          path: _build/${{ env.MIX_ENV }}
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix format --check-formatted

  test:
    name: Run Tests & Submit Coverage

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: '.tool-versions'
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v3
        with:
          path: _build/${{ env.MIX_ENV }}
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix coveralls.github || mix test
        env:
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  credo:
    name: Check Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: '.tool-versions'
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v3
        with:
          path: _build/${{ env.MIX_ENV }}
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix credo --strict

  dialyzer_plt:
    name: Generate Dialyzer PLT

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev
      DIALYZER_PLT_PRIV: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: '.tool-versions'
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v3
        with:
          path: _build/${{ env.MIX_ENV }}
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - uses: actions/cache@v3
        with:
          path: priv/plts/
          key: dialyzer_plt_dev-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            dialyzer_plt_dev-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix dialyzer --plt
      - uses: actions/upload-artifact@v3
        with:
          name: dialyzer_plt_dev
          path: priv/plts/

  dialyzer_test:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    needs: ['dialyzer_plt']

    env:
      MIX_ENV: dev
      DIALYZER_PLT_PRIV: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: '.tool-versions'
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v3
        with:
          path: _build/${{ env.MIX_ENV }}
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - uses: actions/download-artifact@v3
        with:
          name: dialyzer_plt_dev
          path: priv/plts/
      - run: mix dialyzer
