on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

permissions:
  contents: read

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_build.yml
    with:
      attest: false

  docs:
    name: "Docs"

    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_docs.yml
    with:
      attest: false

  dependabot:
    name: "Dependabot"

    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.actor == 'dependabot[bot]'}}

    uses: ./.github/workflows/part_dependabot.yml

  report_deps:
    name: "Report Dependencies"

    needs: ['build']

    permissions:
      contents: write

    uses: ./.github/workflows/part_report_deps.yml

  dependency-review:
    name: "Dependency Review"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0